services:
  - type: web
    name: ChatBookAI-Render
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        sync: false
      - key: LANGCHAIN_PROJECT
        sync: false
      - key: GENAI_API_KEY
        sync: false