name: gsu_chatbot_app
description: A chatbot app for GSU Student Handbook
# tells Dart not to publish this package to pub.dev since it’s a private project.
publish_to: 'none'

# version of the Dart SDK
environment:
  # ^3.9.0 means use any version from 3.9.0 up to (but not including) 4.0.0
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  # Lets your app send requests to APIs (like your chatbot backend)
  http: ^1.2.2
  # Apple-style icons (used for iOS design)
  cupertino_icons: ^1.0.8

  # set width/height of the app window
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

# Development-Only Dependencies
dev_dependencies:
  # For writing and running automated tests
  flutter_test:
    sdk: flutter
  # Helps enforce good coding style and prevent errors
  flutter_lints: ^6.0.0
  # Automatically generates app icons for Android, iOS, and desktop
  flutter_launcher_icons: ^0.14.1

# the modern, standard UI style for Android apps (buttons, text fields, etc.)
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
  macos:
    generate: true
  image_path: "assets/images/ChatBookAILogoAppIcon.png"