name: gsu_chatbot_app
description: A chatbot app for GSU Student Handbook
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8

  # Only one window_size declaration (Git version recommended for desktop dev)
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
  image_path: "assets/images/ChatBookAILogoAppIcon.png"